_BASE_: "../BaseRetina.yaml"
OUTPUT_DIR: "work_dirs/model_test"

MODEL:
  META_ARCHITECTURE: "RetinaNetQueryDet"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  
  RESNETS:
    DEPTH: 50
  
  ANCHOR_GENERATOR:
    NAME: "AnchorGeneratorWithCenter"
    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3)] for x in [16, 32, 64, 128, 256, 512]]"]
  
  RETINANET:
    IOU_THRESHOLDS: [0.4, 0.5]
    IOU_LABELS: [0, -1, 1]
    NUM_CLASSES: 10
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6", "p7"]  
    SCORE_THRESH_TEST: 0.0001
    
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]

  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  
  QUERY:
    FEATURES_WHOLE_TEST: [2, 3, 4, 5]
    FEATURES_VALUE_TEST: [0, 1]
    Q_FEATURE_TRAIN: [1, 2]
    Q_FEATURE_TEST: [1, 2]
    
    ENCODE_CENTER_DIS_COEFF: [1., 1.]
    ENCODE_SMALL_OBJ_SCALE: [[0, 32], [0, 64]]

    THRESHOLD: 0.12
    QUERY_INFER: False
  
  CUSTOM: 
    USE_SOFT_NMS: False
    SOFT_NMS_METHOD: 'gaussian'
    SOFT_NMS_SIGMA: 0.6
    SOFT_NMS_THRESHOLD: 0.4
    SOFT_NMS_PRUND: 0.0001

VISDRONE:
  TEST_LENGTH: 3999

TEST:  
  DETECTIONS_PER_IMAGE: 500

META_INFO:
  EVAL_GPU_TIME: True
