_BASE_: "../BaseRetina.yaml"
OUTPUT_DIR: "work_dirs/visdrone_retinanet"

MODEL:
  META_ARCHITECTURE: "RetinaNet_D2"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50

  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3)] for x in [32, 64, 128, 256, 512]]"]
  
  RETINANET:
    IOU_THRESHOLDS: [0.4, 0.5]
    IOU_LABELS: [0, -1, 1]
    NUM_CLASSES: 10
    IN_FEATURES: ["p3", "p4", "p5", "p6", "p7"]

  CUSTOM:
    FOCAL_LOSS_ALPHAS: [0.25, 0.25, 0.25, 0.25, 0.25]
    FOCAL_LOSS_GAMMAS: [2.0, 2.0, 2.0, 2.0, 2.0]
    CLS_WEIGHTS: [1., 1., 1., 1., 1.]
    REG_WEIGHTS: [1., 1., 1., 1., 1.]

SOLVER:
  BASE_LR: 0.01
  STEPS: (30000, 40000)
  MAX_ITER: 50000
  IMS_PER_BATCH: 8
  AMP:
    ENABLED: True

TEST:  
  EVAL_PERIOD: 0
  DETECTIONS_PER_IMAGE: 500

VIS_PERIOD: 0