_BASE_: "../BaseRetina.yaml"
OUTPUT_DIR: "work_dirs/model_test"

MODEL:
  META_ARCHITECTURE: "RetinaNet_D2"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50

  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3)] for x in [32, 64, 128, 256, 512]]"]

  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  
  RETINANET:
    IOU_THRESHOLDS: [0.4, 0.5]
    IOU_LABELS: [0, -1, 1]
    NUM_CLASSES: 10
    IN_FEATURES: ["p3", "p4", "p5", "p6", "p7"]
    SCORE_THRESH_TEST: 0.005

META_INFO:
  EVAL_GPU_TIME: True


TEST:  
  DETECTIONS_PER_IMAGE: 500
