blank_issues_enabled: true
contact_links:
  - name: 📄 Docs
    url: https://docs.ultralytics.com/yolov5
    about: Full Ultralytics YOLOv5 Documentation
  - name: 💬 Forum
    url: https://community.ultralytics.com/
    about: Ask on Ultralytics Community Forum
  - name: 🎧 Discord
    url: https://discord.gg/n6cFeSPZdD
    about: Ask on Ultralytics Discord
